apiVersion: v1
kind: Template
metadata:
  name: spm-engine-listener

parameters:
  - name: IMAGE_NAMESPACE
    displayName: Image namespace
  - name: IMAGE_TAG
    displayName: Image tag
    value: latest
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels: { app: spm-engine }
      name: spm-engine-listener
    spec:
      replicas: 1
      selector:
        app: spm-engine
        deploymentconfig: spm-engine-listener
      template:
        metadata:
          labels:
            app: spm-engine
            deploymentconfig: spm-engine-listener
          name: spm-engine-listener
        spec:
          containers:
            - image: ${IMAGE_NAMESPACE}/spm-engine-listener:${IMAGE_TAG}
              imagePullPolicy: Always
              name: spm-engine-listener
              command: [ ./listener/entrypoint.sh ]
              resources:
                limits: { cpu: 500m,  memory: 512Mi }
                requests: { cpu: 200m, memory: 512Mi }
              env:
                - { name: KAFKA_HOST, value: platform }
                - { name: KAFKA_PORT, value: "9092" }
                - { name: KAFKA_GROUP, value: spm }
                - { name: UPLOAD_TOPIC, value: platform.upload.available }
                - { name: EVENTS_TOPIC, value: platform.inventory.events }
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - spm-engine-listener
            from:
              kind: ImageStreamTag
              name: spm-engine-listener:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spm-engine
      name: spm-engine-listener
    spec:
      type: ClusterIP
      ports:
        - name: 8081-tcp
          port: 8081
          protocol: TCP
          targetPort: 8081
      selector:
        app: spm-engine
        deploymentconfig: spm-engine-listener

